image: docker:23.0.1
services:
  - docker:23.0.1-dind

stages:
  - build
  - test
  - push

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

postgres:11-3.5:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:11-3.5" --platform linux/amd64,linux/arm64/v8 --push 11-3.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:11-3.5-alpine:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:11-3.5-alpine" --platform linux/amd64,linux/arm64/v8 --push 11-3.5/alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:12-3.5:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:12-3.5" --platform linux/amd64,linux/arm64/v8 --push 12-3.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:12-3.5-alpine:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:12-3.5-alpine" --platform linux/amd64,linux/arm64/v8 --push 12-3.5/alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:13-3.5:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:13-3.5" --platform linux/amd64,linux/arm64/v8 --push 13-3.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:13-3.5-alpine:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:13-3.5-alpine" --platform linux/amd64,linux/arm64/v8 --push 13-3.5/alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:14-3.5:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:14-3.5" --platform linux/amd64,linux/arm64/v8 --push 14-3.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:14-3.5-alpine:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:14-3.5-alpine" --platform linux/amd64,linux/arm64/v8 --push 14-3.5/alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:15-3.5:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:15-3.5" --platform linux/amd64,linux/arm64/v8 --push 15-3.5
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success

postgres:15-3.5-alpine:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --pull --tag "$CI_REGISTRY_IMAGE:15-3.5-alpine" --platform linux/amd64,linux/arm64/v8 --push 15-3.5/alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success
