name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/Dockerfile"
  workflow_dispatch:
env:
  IMAGE_NAME: zkoesters/postgres-pgq
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '13-3.5'
            context: '13-3.5'
          - version: '13-3.5-alpine'
            context: '13-3.5/alpine'
          - version: '14-3.5'
            context: '14-3.5'
          - version: '14-3.5-alpine'
            context: '14-3.5/alpine'
          - version: '15-3.5'
            context: '15-3.5'
          - version: '15-3.5-alpine'
            context: '15-3.5/alpine'
          - version: '16-3.5'
            context: '16-3.5'
          - version: '16-3.5-alpine'
            context: '16-3.5/alpine'
          - version: '17-3.5'
            context: '17-3.5'
          - version: '17-3.5-alpine'
            context: '17-3.5/alpine'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          annotations: ${{ steps.meta.outputs.annotations }}
          sbom: true
          provenance: mode=max
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.version }}