name: Tests
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/Dockerfile"
permissions:
  contents: read
jobs:
  test:
    name: Image Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '13-3.5'
          - version: '14-3.5'
          - version: '15-3.5'
          - version: '16-3.5'
          - version: '17-3.5'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: make test-${{ matrix.version }}
